### ISSUE TITLE
Python 3.9 wheels missing

### ISSUE THREAD

**Issue by PrimozGodec** [vpodpecan/lemmagen3#1]
I notice that wheels for Python3.9 are missing at PyPI. I would be very happy if you can provide them. If you need any help please let me know. If you want I can implement automatic wheel building on Github Actions. So that wheels build automatically when you make a new release.

**Comment by vpodpecan** [comment]
With the just released v3.3.2 wheels are now available for python 3.6 up to 3.10 RC1. Please test and report any issues. I am now closing this issue.

**Comment by PrimozGodec** [comment]
Thanks for the fast response Vid
